# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/115LsObeoN4KsVFdGw8BhOEJ8X7VoSRlK
"""

import numpy as np
from sklearn.neighbors import KNeighborsRegressor

class DataProcess:
    def __init__(self):
        # Empty the list
        self.points = np.empty((0, 2), dtype=float)

    def int_check(self, num):
        # Check if it is positive int
        while True:
            try:
                val = int(num)
                if val <= 0:  # if the input is negative
                    num = input("Input must be a positive integer, try again! Enter number: ")
                    continue
                break
            except ValueError:  # if the input is not integer
                num = input("Input must be a integer, try again! Enter number: ")
        n = val
        return n

    def realnumber_check(self, question):
        # Check if it is positive int
        while True:
            try:
                return float(input(question))
            except ValueError:
                print("Invalid input. Please enter a valid number.")

    def type_number(self, question):
        # Ask for the number and then run "int_check" to check if it is positive int
        n = input(question)
        return self.int_check(n)


class KNN:
    def __init__(self):
        self.points = []
        self.labels = []

    def insert_point(self, x, y):
        self.points.append([x, y])
        self.labels.append([y])

    def calculate_knn(self, x, k):
        # Calculate the X distances
        array_points = np.array(self.points)
        knn = KNeighborsRegressor(n_neighbors=k)
        knn.fit(array_points[:, 0].reshape(-1, 1), array_points[:, 1])
        y_pred = knn.predict([[x]])
        return y_pred[0]

    def variance_labels(self):
        return np.var(self.labels)

Data_Process = DataProcess()
kNN = KNN()
N = Data_Process.type_number("Enter the number of numbers (N): ")
print(f"N = {N}")
k = Data_Process.type_number("Enter the k value: ")
print(f"k = {k}")
for i in range(N):
    x = Data_Process.realnumber_check(f"Enter x for Point #{i + 1}: ")
    y = Data_Process.realnumber_check(f"Enter y for Point #{i + 1}: ")
    kNN.insert_point(x, y)
for i in range(N):
    print(f"Point #{i+1} : [{kNN.points[i][0]}, {kNN.points[i][1]}]")
# Ask for the number X
X = Data_Process.realnumber_check("Enter the number X: ")
if k > N:
    print("Error: k cannot be greater than the number of points (N)")
else:
    result = kNN.calculate_knn(X, k)
    print(f"The predicted Y-value at X = {X} using {k}-NN regression is: {result}")
    variance = kNN.variance_labels()
    print(f"Variance of labels in the training dataset: {variance}")

"""# New Section"""